name: Extension Deployment

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the new extension version and upload it the Chrome and Firefox stores.
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - name: npm run deploy
      env:
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        API_KEY: ${{ secrets.FIREFOX_JWT_ISSUER }}
        API_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
      run: |
        npm run deploy
